services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifevisor
    ports:
      - 5432:5432
  backend:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres dbname=lifevisor sslmode=disable timezone=UTC connect_timeout=5"
