apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: lifevisor-metabase-postgres
  name: lifevisor-metabase-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lifevisor-metabase-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o ./kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: lifevisor-metabase-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: metabaseappdb
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: metabase
          image: postgres:latest
          name: lifevisor-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: lifevisor-metabase-db-data
      restartPolicy: Always
      volumes:
        - name: lifevisor-metabase-db-data
          persistentVolumeClaim:
            claimName: lifevisor-metabase-db-data
