apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: lifevisor-metabase-db-data
  name: lifevisor-metabase-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
